# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DeCasteljau_cpp <- function(rsegments, keyTimes, times) {
    .Call(`_qs_DeCasteljau_cpp`, rsegments, keyTimes, times)
}

rversor_cpp <- function(n) {
    .Call(`_qs_rversor_cpp`, n)
}

